### ISSUE TITLE
error when getting annotation points cordinate in some images

### ISSUE THREAD

**Issue by StasMakarchuk** [cellgeni/GBM-stuff#5]
```
 points = [(lambda xy : list(map(float,xy.split(","))))(xy) for xy in primary_shape.getPoints().val.split(" ")] 
File "/home/ubuntu/anaconda3/envs/GBM/lib/python3.9/site-packages/omero_model_LabelI.py", line 643, in __getattr__
raise AttributeError("'%s' object has no attribute '%s' or '%s'" % (self.__class__.__name__, getter, questn))
AttributeError: 'LabelI' object has no attribute 'getGetPoints' or 'isGetPoints'
```
possibly it is due to different version of SpaceRanger

**Comment by prete** [comment]
That errror means is failing because the ROI (OMERO annotation) is a Label, not a Polygon. 
Polygons have points (`primary_shape.getPoints()`) whereas Labels [see Label model](https://omero.readthedocs.io/en/stable/developers/Model/EveryObject.html#label) dont' have them, they only have `x` and `y` propreties.

**Comment by StasMakarchuk** [comment]
I just skip all Labels and print infor about in

**Comment by StasMakarchuk** [comment]
resolved

**Comment by prete** [comment]
Sounds about right. For future references, I think `omero.model.RectangleI` and `omero.model.EllipseI` won't have a `points` property either and may throw a similar error.
